src/integ/groovy/com/msgilligan/bitcoin/rpc/BitcoinRawTransactionSpec.groovy, src/integ/groovy/com/msgilligan/bitcoin/rpc/BitcoinSpec.groovy, src/main/groovy/org/mastercoin/test/TestSupport.groovy, src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
New or updated methods:
- BigDecimal getBitcoinBalance(Address address)
- BigDecimal getBitcoinBalance(Address address, Integer minConf, Integer maxConf)
- List\<Map\<String, Object>> listUnspent()
- List\<Map\<String, Object>> listUnspent(Integer minConf, Integer maxConf)
- List\<Map\<String, Object>> listUnspent(Integer minConf, Integer maxConf, Iterable\<Address> filter)
- Map\<String, Object> signRawTransaction(String unsignedTransaction)
- Sha256Hash sendRawTransaction(String hexTx)
- String createRawTransaction(Address fromAddress, Address toAddress, BigDecimal amount)
- String createRawTransaction(Address fromAddress, Map\<Address, BigDecimal> outputs)
- String createRawTransaction(List\<Object> inputs, Map\<Address, BigDecimal> outputs)
Most of it is in action in the specification …
=> Native support for raw transaction handling

src/integ/groovy/com/msgilligan/bitcoin/rpc/BitcoinRawTransactionSpec.groovy, src/main/groovy/org/mastercoin/test/TestSupport.groovy
Refined:
- String createRawTransaction(Address fromAddress, Map<Address, BigDecimal> outputs)
New:
- Sha256Hash sendBitcoin(Address fromAddress, Address toAddress, BigDecimal amount)
- Sha256Hash sendBitcoin(Address fromAddress, Map\<Address, BigDecimal> outputs)
Test:
- BitcoinRawTransactionSpec: "Send Bitcoin"
=> Add and test "sendBitcoin" to transfer BTC without new change address

src/integ/groovy/org/mastercoin/test/rpc/MSCSimpleSendSpec.groovy, src/main/java/org/mastercoin/CurrencyID.java, src/main/java/org/mastercoin/Ecosystem.java, src/main/java/org/mastercoin/PropertyType.java, src/main/java/org/mastercoin/rpc/MastercoinClient.java, src/test/groovy/org/mastercoin/CurrencyIDSpec.groovy, src/test/groovy/org/mastercoin/EcosystemSpec.groovy
There were a few places where a number was converted into a too small type.
When sending a very small amount via send_MP (...) it would have been converted
into "9.9E-7" instead of "0.00000099" before sending, thus "toPlainString" was
used.
The "native" Master/Omni type objects (CurrencyID, Ecosystem, PropertyType) have
two constructors now: one for the underlying value type, and one that can be
called with the more general "Number" interface.
The "Number" interface is also used for the property creation, where no "native"
type object (in this case "Number of Coins") is yet in place, so it doesn't
matter, whether it's called with an "Integer", "Long", "BigDecimal", etc., which
are converted into a hex string anyway.
"Ecosystem" and "PropertyType" have a "toString" method, which simply …
=> Tweak type handling

src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToOwnersSpec.groovy, src/main/groovy/foundation/omni/test/TestSupport.groovy
Similar to createProperty, createPropertyHex, createDexSellOffer and createDexSellOfferHex,
this PR adds support for creating raw STO transactions.
This is useful to bypass the RPC layer.
TestSupport:
- Sha256Hash sendToOwners(Address address, CurrencyID currencyId, Long amount)
- String createSendToOwnersHex(CurrencyID currencyId, Long amount)
MSCSendToOwnersSpec:
- "The generated hex-encoded transaction matches a valid reference transaction"
=> Support creating STO transaction based on raw transaction data

src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToManyOwnersSpec.groovy, src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToOwnersTestPlanSpec.groovy, src/main/java/foundation/omni/CurrencyID.java, src/test/groovy/foundation/omni/CurrencyIDSpec.groovy
See #34 regarding the CurrencyID and Bitcoin.
This PR adds the missing invalidation tests for "send to owners":
- STO Property ID is non-existent
- STO Property ID is 0 - bitcoin
- Sender owns all the coins of the STO Property, other addresses had non-zero balances but now zero balances
It integrates well into the test setup and the tests can also be tested with raw transactions, when running the -TestPlanRawSpec.
Two tests are ignored until #35 is solved.
=> Finalize STO test plan and add missing tests

src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToOwnersTestPlanSpec.groovy, src/main/groovy/foundation/omni/test/TestSupport.groovy, src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
This PR finalizes the "send to owner" invalidation tests (#18) and improves bitcoin related funding (#35).
Instead of "sendtoaddress", newly mined coins are explicitly selected and spent.
=> Finish #18: STO invalidation, fix #35: BTC related funding

src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToOwnersTestPlanSpec.groovy, src/integ/groovy/foundation/omni/test/rpc/sto/sto-testplan.tsv, src/main/groovy/foundation/omni/test/TestSupport.groovy, src/main/java/foundation/omni/CurrencyID.java, src/test/groovy/foundation/omni/CurrencyIDSpec.groovy
See #39.
This further adds `CurrencyID.valueOf(String s)` and `Sha256Hash requestMSC(Address toAddress, BigDecimal requestedMSC)`.
This later could be used in combination with `requestBTC` to break down and remake `createFundedAddress`.
=> STO invalidation test: actor has not enough TMSC to pay for fees

bitcoin.conf, test-btc-integ-regtest.sh, test-msc-consensus-mainnet.sh, test-msc-integ-regtest.sh
- Bitcoin Core 0.10 doesn't allow wildcards for `-rpcallowip`
- The options `--server` and `-debug` are shared by all three scripts
- The option `-logtimestamps` adds additional debug information
=> Update bitcoin.conf and test scripts

src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToManyOwnersSpec.groovy
The error is likely caused, because "sendtoaddress"' coin selection selects too many inputs, likely trying to spend all the dust created earlier.
As first fix I tried `sendToAddress(newAddress, getBalance() - 0.1)` to force dust sweeping after each STO round. Because we no longer fund BTC via "sendtoaddress", it might be safe to remove this workaround, which actually causes an error in this case.
=> Try fix to avoid "Transaction too large" error

src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, src/main/groovy/foundation/omni/test/TestSupport.groovy
... to prevent the creation of too large transactions.
See: https://github.com/msgilligan/bitcoin-spock/issues/50
=> RegTests: cleanup and sweep unspent outputs

src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
With Bitcoin Core 0.10 the result of "setgenerate" is no longer empty, but a list of block hashes. To support 0.9 and 0.10, returning an Object seems to be the middle ground, as mentioned in #44.
=> BitcoinClient: return result of setGenerate() as Object

src/integ/groovy/foundation/omni/test/rpc/sto/SendToManyOwnersSpec.groovy
Given that each round is currently executed twice, once to print debug information and another time to actually test results, but STO is fairly tested at this point, the dry debug runs should be disabled by default.
=> SendToManyOwnersSpec: disable debug runs

bitcoin-rpc/src/integ/groovy/com/msgilligan/bitcoin/rpc/BitcoinSpec.groovy, bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToManyOwnersSpec.groovy
See commit details:
- Move magic number of owners in "send to many owners" test to the top
- Set transaction fee and assert transaction relay fees in regtest mode
- Support RPC "help" and listing of all available RPC commands
=> Enforce transaction relay fee settings and support listing of RPC commands

bitcoin-rpc/build.gradle, bitcoin-rpc/src/integ/groovy/com/msgilligan/bitcoin/BaseRegTestSpec.groovy, bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java, omnij-rpc/build.gradle, omnij-rpc/src/integ/groovy/foundation/omni/BaseMainNetSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy
Example output of omnij-rpc:regTest:
<pre>
<b>foundation.omni.test.rpc.basic.SendRawTransactionSpec</b>
Create raw transaction with reference address
Create raw transaction without reference address
<b>foundation.omni.test.rpc.basic.OmniSpec</b>
Implement getbalance_MP
Return Master Core version field using getinfo_MP
<b>foundation.omni.test.rpc.dex.DexSpec</b>
A new sell offer can be created with Action = 1 (New)
An accepted currency identifier for sell offers is CurrencyID:1
An accepted currency identifier for sell offers is CurrencyID:2
Offering more tokens than available puts up an offer with the available amount
...
</pre>
See #68 for the discussion.
=> Reduce visibility of RPC status messages, format regtest output

bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/BaseReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SimpleSendReorgSpec.groovy
This PR adds the required RPC calls (and some related) to test block reorganzations.
The tested transaction types and aspects of Omni Core are:
- simple send
- send to owners
- property creation
There are two significant downsides: the `"invalidateblock"` command was introduced with Bitcoin Core 0.10, and is therefore not available on the CI server, but worse: I had no handy way to clear the memory pool, and added an [extra extension](https://github.com/dexX7/bitcoin/compare/e687023daf4c4720d6804d7dcc51b8df2bc55684...dexX7:oc-0.10-rpc-clearmempool) for this.
All reorganization tests are skipped, if `"clearmempool"` is not available, or if `"setgenerate"` doesn't return a list of block hashes, indicating a client version, which is not based on 0.10.
I'm not sure, if this PR should be …
=> Add RPC commands and tests for block reorganizations

bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
- The changes to `BitcoinClient` are limited to documentation and code format, except for `"getnewaddress"`, where a paramter list was created, but not used.
- `OmniClient` was extended with new RPC calls for the token exchange, and `createParamList` was used to unify the parameter handling.
- RPC commands, which are only available to newer Bitcoin and Omni Core clients, are tagged with `@since <client> <version>`.
- A helper was added to check, whether a command exists.
- A very simple test for the distributed exchange was added, where an offer is created. The test is skipped, if the required commands are not available.
=> RPC documentation improvements, token exchange preparations

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SimpleSendSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/misc/ClientConfigurationAndFundingSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
Due to updates of Omni Core, in particular class C support and a change of `trade_MP`, the commits of this PR are required, to prevent test failures.
It's backwards compatible, and does not affect the current production version 0.0.9.
=> Keep up with Omni Core's interface changes and updates

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CloseCrowdsaleSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniExtendedClient.java
Transaction type 53 (close crowdsale):
- "Closing a non-existing crowdsale is invalid"
- "Closing a non-crowdsale is invalid"
- "A crowdsale can not be closed by a non-issuer"
- "Before closing a crowdsale, tokens can be purchased"
- "A crowdsale can be closed with transaction type 53"
- "A crowdsale can only be closed once"
- "Sending tokens, after a crowdsale was closed, does not grant tokens",
Transaction type 55 (grant tokens for managed property):
- "It's impossible to grant tokens for an non-existing property"
- "Granting tokens for a property with fixed supply is invalid"
Transaction type 56 (revoke  tokens for managed property):
- "It's impossible to revoke tokens for an non-existing property"
- "Revoking tokens for a property with fixed supply is invalid""
=> Additional tests for transaction type 53, 55 and 56

bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java, omnij-rpc/src/integ/groovy/foundation/omni/BaseMainNetSpec.groovy
As described in https://github.com/OmniLayer/OmniJ/issues/74#issuecomment-116428633:
- status messages are logged only once, if new or updated
- status messages are logged as `INFO`
- begin and end of waiting is logged as `DEBUG`
=> Refine waitForServer() logging

bitcoin.conf
The speed of the initial parsing can be increased by skipping predefined blocks.
Parsing with enabled skipping is less thorough though.
Since OmniJ/CI server is all about testing, we probably don't want this.
@msgilligan: if this config file isn't consumed by the CI server, it would be great, if you could update the scripts and include `omniseedblockfilter=0` in the `bitcoin.conf`, or use `-omniseedblockfilter=0` as command-line option.
The related PR is https://github.com/OmniLayer/omnicore/pull/135.
=> Don't skip blocks during initial parsing

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendall/SendAllSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
Specification:
- All available tokens can be transferred with transaction type 4
- "Send All" transactions are only valid, if at least one token was transferred
- Only available, unreserved balances are transferred with "Send All"
The tests are only executed, if the client has the RPC call "omni_sendall".
Two tests for managed properties were enabled, which are available for Omni Core 0.0.10.
Related: https://github.com/OmniLayer/omnicore/pull/155
=> Add tests for "Send All" transaction type

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendall/SendAllSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
The new transaction format is:
[version: 0] [type: 4] [ecosystem]
Related commit: https://github.com/OmniLayer/omnicore/commit/de3bcd62642b5f6c2e89c453628b74c18b5ec482
=> Support ecosystem parameter for "send all" transactions

bitcoin-rpc/src/integ/groovy/com/msgilligan/bitcoinj/WalletSendSpec.groovy, bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/BTC.java, omnij-core/src/main/java/foundation/omni/CurrencyID.java, omnij-core/src/main/java/foundation/omni/Ecosystem.java, omnij-core/src/main/java/foundation/omni/OmniDivisibleValue.java, omnij-core/src/main/java/foundation/omni/OmniIndivisibleValue.java, omnij-core/src/main/java/foundation/omni/OmniValue.java, omnij-core/src/main/java/foundation/omni/PropertyType.java, omnij-core/src/main/java/foundation/omni/tx/RawTxBuilder.java, omnij-core/src/test/groovy/foundation/omni/CurrencyIDSpec.groovy, omnij-core/src/test/groovy/foundation/omni/EcosystemSpec.groovy, omnij-core/src/test/groovy/foundation/omni/OmniAmountSpec.groovy, omnij-core/src/test/groovy/foundation/omni/OmniDivisibleValueSpec.groovy, omnij-core/src/test/groovy/foundation/omni/OmniIndivisibleValueSpec.groovy, omnij-core/src/test/groovy/foundation/omni/OmniValueSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/ConsensusSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendall/SendAllSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/consensus/ChestConsensusTool.groovy, omnij-rpc/src/main/groovy/foundation/omni/consensus/OmniwalletConsensusTool.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rpc/src/main/java/foundation/omni/rpc/OmniExtendedClient.java
* Simplify and move away from BTC utility class where possible
* Make better use of bitcoinj Coin class where possible
* Ecosystem and PropertyType no longer extend Number
* Use getValue() rather than byteValue(), shortValue(), etc
* Make some constructors private, e.g. Ecosystem, PropertyType
* Use .of() method for creating Omni*Value types
* .asWillets() method for extracting willet internal/wire representation
* Consistently use ArithmeticException (not NumberFormatException)
* Add important design note JavaDoc to OmniValue class
=> Refactoring of several Number and enum-style classes

omnij-rpc/src/integ/groovy/foundation/omni/BaseMainNetSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/ConsensusSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/ListPropertiesSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/OmniSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SendRawTransactionSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SimpleSendSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CloseCrowdsaleSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CrowdsaleParticipationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/exodus/MoneyManSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/misc/ClientConfigurationAndFundingSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/BaseReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SimpleSendReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendall/SendAllSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/SmartPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToManyOwnersSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanRawSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/tx/OmniTxBuilderIntegSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/consensus/OmniCoreConsensusTool.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/MPBalanceEntry.java, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rpc/src/main/java/foundation/omni/rpc/OmniExtendedClient.java, omnij-rpc/src/main/java/foundation/omni/rpc/SmartPropertyListInfo.java
This PR adds a bunch of new methods, and updates already existing methods, to access the Omni Core RPC API:
- https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md
If the RPC is `"omni_getbalance"`, then the corresponding method name is `omniGetBalance()`, if the RPC is `"omni_senddexsell"`, then the method name is `omniSendDExSell()` and so on.
=> Add, replace and use Omni Core 0.0.10 RPC API

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/ListPropertiesSpec.groovy
The token description of MSC and TMSC changed in Omni Core 0.0.10, and as result this test breaks the automated testing of Omni Core.
Once Master Core 0.0.9 is depreciated, the test can be updated and re-enabled.
See: https://github.com/OmniLayer/omnicore/pull/217#issuecomment-137170515
=> Ignore test for "listproperties_MP" RPC

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/BaseActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/GracePeriodSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/MetaDExActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/OverOfferDeactivationSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
**Add support for RPC "omni_sendactivations" to activate features**
The command can be used to activate protocol features, and is going to be added in Omni Core 0.0.10.
**Add support for RPC "omni_getactivations"**
This command can be used to list pending or completed activations, and is going to be added in Omni Core 0.0.10.
**Add specification for the grace period of feature activations**
Features are activated at specific block heights, which must be within the range of a grace period to ensure users have enough time to update their clients.
The use of activation commands is restricted to whitelisted senders. To whitelist a source to allow feature activations, the option `-omniactivationallowsender="sender"` can be used.
The option `-omniactivationallowsender=any` can be used to remove …
=> Add tests and helpers related to feature activations

build.gradle, omnij-cli/build.gradle, omnij-core/src/main/java/foundation/omni/OmniDivisibleValue.java, omnij-core/src/main/java/foundation/omni/OmniIndivisibleValue.java, omnij-core/src/main/java/foundation/omni/OmniValue.java, omnij-core/src/main/java/foundation/omni/test/MoneyMan.java, omnij-core/src/test/groovy/foundation/omni/OmniDivisibleValueSpec.groovy, omnij-dsl/build.gradle, omnij-dsl/src/main/groovy/foundation/omni/dsl/categories/NumberCategory.groovy, omnij-dsl/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule, omnij-dsl/src/test/groovy/foundation/omni/dsl/categories/NumberCategorySpec.groovy, omnij-rpc/build.gradle, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SendRawTransactionSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SimpleSendSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/exodus/MoneyManSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/misc/ClientConfigurationAndFundingSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/SmartPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanRawSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/tx/OmniTxBuilderIntegSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/rpc/OmniCLIClient.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniExtendedClient.java, settings.gradle
This PR is partial conversion, but @dexX7 if you think it's OK to merge it to master, I'd like to do so. There are a lot of changes and I'd rather not have to keep merging them.
regTests are currently passing.
=> Begin conversion from BigInteger to OmniValue and Coin

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CrowdsaleParticipationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexVersionsSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
The new or updated tests cover some of the pitfalls we recently had with Omni Core.
In particular:
- https://github.com/OmniLayer/omnicore/issues/242 Reorg containing STO corrupts STODB data
- https://github.com/OmniLayer/omnicore/pull/187#issuecomment-133244564 Reorg may cause token IDs to drift
- https://github.com/OmniLayer/omnicore/issues/235 Crowdsale participations being classified as simple sends
- https://github.com/OmniLayer/omnicore/issues/241 Action of DEx orders differs between 0.0.9 and 0.0.10
- https://github.com/OmniLayer/omnicore/commit/5d550f0aa068685703423169684c4742ac03ceaa Add special handling when parsing v0 trade offers
- https://github.com/OmniLayer/omnicore/issues/200 Remaining amount of MetaDEx trade is not updated
There are a few related improvements, which I …
=> Update tests to increase coverage of RPC results and core

omnij-rpc/build.gradle, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/BaseActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/GracePeriodSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/MetaDExActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/OverOfferDeactivationSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy
Activating a feature more than once is not allowed, and the activation tests are skipped, if the feature to test is already activated.
Feature activation tests are split into a seperate task, which is executed before running the `:omnij-rpc:regTest` task. This ensures features, if necessary, are activated before the tests are executed, which may depend on the feature.
The new class `IntegrationTest` is used to set reusable properties, such as the test log formatting, and the new class `RegTest` is intended to be used for RPC tests in regtest mode.
Test failures are described in greater detail, in a similar fashion as in the test reports, where the actual cause (e.g. a failed condition) is printed:
```
...
foundation.omni.test.rpc.basic.ConsensusSpec
Check all balances
Check all balances, …
```
=> Improve handling of integration tests and feature activations

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CrowdsaleParticipationSpec.groovy
Because TMSC are traded, the crowdsale should be in the test ecosystem.
This resolves an upstream issue: https://github.com/OmniLayer/omnicore/pull/252#issuecomment-141841171
=> Fix typo in crowdsale test and cleanup crowdsales

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/OverOfferDeactivationSpec.groovy
It looks like 320417b886ff36eb1d9e9925121f1952fb1e07ae introduced a bug.
The test is for an unmerged Omni Core PR, and the issue was not caught by the standard tests.
=> Fix OverOfferDeactivationSpec after OmniValue update

.travis.yml, test-omni-integ-regtest.sh
The developer preview of Omni Core is downloaded from Omni Chest, and the tests in regtest mode are executed via the test script.
=> Run tests in regtest mode via Travis CI

test-omni-integ-regtest.sh
The minimum relay fee was temporarily raised to make it harder to spam and bloat the mempool. This however conflicts with some regtests, so fixed/reference fees are explicitly provided.
Related: https://github.com/OmniLayer/omnicore/pull/263
=> Explicitly set transaction and relay fees for regtests

adoc/release-process.adoc, build.gradle, omnij-cli/src/main/groovy/foundation/omni/cli/ConsensusCLI.groovy, omnij-core/src/main/java/foundation/omni/OmniValue.java, omnij-dsl/src/test/groovy/foundation/omni/dsl/categories/NumberCategorySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/ChestServerSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/GetBalancesSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SimpleSendSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CloseCrowdsaleSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/crowdsale/CrowdsaleParticipationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/consensus/ChestConsensusTool.groovy, omnij-rpc/src/main/groovy/foundation/omni/consensus/OmniwalletConsensusTool.groovy, omnij-rpc/src/main/java/foundation/omni/json/conversion/AddressBalanceEntriesDeserializer.java, omnij-rpc/src/main/java/foundation/omni/json/conversion/OmniClientModule.java, omnij-rpc/src/main/java/foundation/omni/json/conversion/OmniValueDeserializer.java, omnij-rpc/src/main/java/foundation/omni/rpc/AddressBalanceEntry.java, omnij-rpc/src/main/java/foundation/omni/rpc/BalanceEntry.java, omnij-rpc/src/main/java/foundation/omni/rpc/OmniExtendedClient.java, omnij-rpc/src/main/java/foundation/omni/rpc/PropertyBalanceEntry.java, omnij-rpc/src/test/groovy/foundation/omni/consensus/ConsensusComparisonSpec.groovy, omnij-rpc/src/test/groovy/foundation/omni/consensus/ConsensusEntryPairSpec.groovy, omnij-rpc/src/test/groovy/foundation/omni/consensus/SnapshotData.groovy, omnij-rpc/src/test/groovy/foundation/omni/json/conversion/AddressBalanceEntriesDeserializerSpec.groovy, omnij-rpc/src/test/groovy/foundation/omni/json/conversion/PropertyBalanceEntriesDeserializerSpec.groovy
@dexX7 I started on this conversion. So far so good, but using `.equals()` instead of `==` is not very nice, but I don't see any real alternative.
=> Convert BalancyEntry from BigDecimal to OmniValue 

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/AllPairDExActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/BaseActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy
This pull request adds tests for the trading of non-Omni pairs.
Once the feature with identifier 8 is active, the distributed token exchange can be used with non-Omni tokens.
During the grace period, the old rules are still in place.
Please note: unfortunally unit prices are no longer nominated in Omni, but instead based on forsale/desired, which is different from our release version.
@msgilligan: ~~currently I simply assume the tests are run with an Omni Core version with the feature and the updated unit price meaning (currently pending as  https://github.com/OmniLayer/omnicore/pull/361), but the tests will fail with 0.0.10. What do you suggest to tackle this? Ideally we'd provide compatibility for both versions.~~
=> Add activation and trading tests for all-pair trading

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/BaseActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/MetaDExFeesActivationSpec.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java
The following new RPCs were added:
- omni_getfeecache
- omni_getfeetrigger
- omni_getfeeshare
- omni_getfeedistribution
- omni_getfeedistributions
This also adds activation tests for the fee distirbution system.
=> Add RPCs and activation test for fee distribution system

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, test-omni-integ-regtest.sh
The mempool chain limit is raised to 750 from the default of 25, because otherwise chains of unconfirmed transactions are limited to 25 transactions, which results in failures in the STO tests.
New BTC are explicitly requested in the STO reorg test, because apparently the sender has no more BTC after reorganizing the chain. It's unclear to me why this is needed in 0.13, but it resolves a test failure locally for me.
=> Prepare OmniJ for Bitcoin Core 0.13 changes

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy
When creating a DEx accept with `omniSendDExAccept`, the transaction fee may not be sufficient, because it uses the global client fee to create the accept transaction. Creating the transaction via Omni Core's RPC layer takes care of the fee handling.
=> Use omniSendDExAccept instead of acceptDexOffer

omnij-cli/src/integ/groovy/foundation/omni/cli/ConsensusCLISpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/SendRawTransactionSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/dex/DexSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/rpc/OmniCLIClient.groovy, omnij-rpc/src/main/groovy/foundation/omni/rpc/OmniClientDelegate.groovy, omnij-rpc/src/main/groovy/foundation/omni/rpc/OmniScriptingClient.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestClientDelegate.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/RegTestContext.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/RegTestOmniFundingSource.groovy, omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rpc/src/main/java/foundation/omni/rpc/test/OmniTestClient.java
* Deprecate OmniExtendedClient and all its methods
* Create OmniTestClient to replace OmniExtendedClient in integration tests
* Create OmniTestClientDelegate trait for use in tests
* OmniCLIClient now extends OmniClient rather than OmniExtendedClient
* Don’t use OmniCLIClient in most tests (use OmniTestClient instead)
* OmniClientDelegate uses OmniClient (not OmniCLIClient)
* OmniScriptingClient uses OmniClient (not OmniExtendedClient)
* Fix issue with omni_senddexsell sending real number not string
(note this is different from how BTC values are sent in standard Bitcoin RPCs)
=> Deprecate OmniExtendedClient

.travis.yml
This pull request resolves #128 and updates the binary used for the Travis CI runs to Omni Core 0.0.11.2.
=> Use Omni Core 0.0.11.2 for Travis CI

test-omni-integ-regtest.sh
Currently BitcoinJ is unable to handle segwit block serialization, which results in test failures. With this option the old format is provided.
=> Use non-segwit serialization for RPC tests

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/basic/ListPropertiesSpec.groovy
The symbols and descriptions for the base tokens Omni and Test Omni changed, so the test is ignored, until the change is merged into a stable version.
This PR is combined with https://github.com/OmniLayer/omnicore/pull/908.
=> Ignore test for description of OMN and TOMN base tokens

test-omni-integ-regtest.sh
The script still referred to the old mastercore.log log file, which was renamed to omnicore.log at some point.
=> Use correct Omni Core log file of Travis CI regtests

omnij-jsonrpc/src/main/java/foundation/omni/rpc/SmartPropertyListInfo.java
Use Jackson annotation to ignore unknown properties.
This is a short-term solution to fix the tests which are currently failing for Omni Core in Git.
Obviously OmniJ will need an additional update to actually make the new fields available to clients. (We should also consider making “ignoreUnknown” JSON properties the default)
=> SmartPropertyListInfo: JSON ignoreUnknown

omnij-core/src/main/java/foundation/omni/address/OmniAddressMainNetParams.java, omnij-core/src/main/java/foundation/omni/address/OmniAddressRegTestParams.java, omnij-core/src/main/java/foundation/omni/address/OmniAddressTestNetParams.java, omnij-core/src/main/java/foundation/omni/address/OmniBase58LegacyAddressConverter.java, omnij-core/src/main/java/foundation/omni/address/OmniSegwitAddressConverter.java, omnij-core/src/test/groovy/foundation/omni/address/OmniBase58LegacyAddressConverterSpec.groovy, omnij-core/src/test/groovy/foundation/omni/address/OmniSegwitAddressConverterSpec.groovy
* Rename and prepare to deprecate experimental Omni Base58 address support
* Add `o` HRP (human readable part) to OmniAddressMainNetParams
* Create OmniAddressTestNetParams with `to` HRP
* Create OmniAddressRegTestParams with `ort` HRP
* Add OMniSegwitAddressConverter class (and test Specification)
=> Prototype Omni Bech32 (safe address) implementation

omnij-jsonrpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rest-client-mjdk/src/main/java/foundation/omni/rest/omniwallet/mjdk/OmniwalletModernJDKClient.java, omnij-rest-client/src/main/java/foundation/omni/rest/omniwallet/OmniwalletClient.java
* OmniClient (JSON-RPC)
* OmniwalletClient (Retrofit)
* OmniwalledModernJDKClient (java.net.http JDK 11)
(We can remove the “ignore unknown” annotations later.)
=> By default ignore unknown JSON props in 3 places:

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/BaseReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/PropertyCreationReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SimpleSendReorgSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/SmartPropertySpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToManyOwnersSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy
and use Coin and OmniDivisible types in callers to use the correct
createFundedAddress() method.
Also rename MSC to OMNI in a few places.
=> Remove deprecated createFundedAddress() overloads

build.gradle, omnij-core/src/test/groovy/foundation/omni/EcosystemSpec.groovy, omnij-rpc/build.gradle, omnij-rpc/src/test/groovy/foundation/omni/json/conversion/AddressBalanceEntriesDeserializerSpec.groovy
Commit 2c22dbcb9d3c1a91ca96d31129002396fd8e9ef3 effectively turned off all unit tests while still allowing the build to complete successfully.
This commit re-enables the unit-tests, but because we've upgrade to Spock 2.0 and JUnit 5 -- some of the tests are now failing.
My recommendation is that we merge this PR to `master` **and** merge another PR that temporarily `@Ignore`s the failing tests. We can then create a branch without the `@Ignore`d tests and resolve the remaining issues on that branch.
=> Enable useJUnitPlaform(), Spock 2.0 fixes

build.gradle
This restores the behavior of `AssumptionViolatedException` resulting
in an ignored test not a failed test.
=> Add spock-junit4 testImplementation dependency

bitcoin.conf, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/RegTestContext.groovy
Keeping this ready for when Omni Core changes its default port for RegTest RPCs.
=> Change tests to use new default RegTest RPC port

.github/workflows/graalvm.yml, .github/workflows/gradle.yml, .github/workflows/regtest.yml, .travis.yml, README.adoc, build.gradle, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, settings.gradle, test-download-omnicore-ubuntu.sh, test-omni-integ-regtest.sh
* If CI, don’t upload Gradle buildscans in background
* Add 3 Github Actions workflows: gradle.yml, regtest.yml, graalvm.yml
* Refactor Omni Core download from .travis.yml to a BASH script named test-download-omnicore-ubuntu.sh
* Add README badges for 3 Github Actions workflows
* GithubCI RegTests upload test results as artifact (on failure, only)
* RegTest increase longerDelayAfterInvalidate (to 120 seconds!)
* Add Gradle caching
*README: Add build note
=> Add Github Actions and enable Gradle build scans

omnij-jsonrpc/src/main/java/foundation/omni/rpc/BalanceEntry.java, omnij-jsonrpc/src/test/groovy/foundation/omni/rpc/BalanceEntrySpec.groovy, omnij-net-api/src/main/java/foundation/omni/netapi/omniwallet/OmniwalletAbstractClient.java
In `BalanceEntry.java`, the “total balance” for an address is now:
`balance` + `reserved`.
When converting from Omniwallet JSON to the Omni Core `BalanceEntry` object,
`frozen` is either zero or equal to `balance`.
=> Fixes to how frozen is handled/totaled.

CHANGELOG.adoc, omnij-core/src/main/java/foundation/omni/CurrencyID.java
Cloneable/clone() should not be necessary for an immutable object and is not a best practice according to Effective Java.
=> CurrencyID: Remove Cloneable and clone()

omnij-core/src/main/java/foundation/omni/OmniOutput.java, omnij-jsonrpc/src/main/java/foundation/omni/json/conversion/OmniClientModule.java, omnij-jsonrpc/src/main/java/foundation/omni/json/conversion/OmniOutputDeserializer.java, omnij-jsonrpc/src/main/java/foundation/omni/json/conversion/OmniOutputSerializer.java, omnij-jsonrpc/src/test/groovy/foundation/omni/json/conversion/OmniOutputJsonSpec.groovy
`omnij-core`:
* OmniOutput: A record-like container for an address and an amount
`omnij-jsonrpc`:
Serialization and deserialization support, added to `OmniClientModule` to be included in the Omni JSON-RPC client.
=> Add OmniOutput with serializer and deserializer

omnij-core/src/main/java/foundation/omni/OmniValue.java, omnij-core/src/test/groovy/foundation/omni/OmniValueSpec.groovy, omnij-jsonrpc/src/main/java/foundation/omni/json/conversion/OmniOutputDeserializer.java, omnij-jsonrpc/src/main/java/foundation/omni/json/conversion/OmniValueDeserializer.java, omnij-jsonrpc/src/main/java/foundation/omni/json/pojo/OmniPropertyInfo.java, omnij-net-api/src/main/java/foundation/omni/netapi/omniwallet/OmniwalletAbstractClient.java, omnij-net-api/src/main/java/foundation/omni/netapi/omniwallet/json/OmniwalletPropertyInfo.java
... as requested by @dexX7 .
I was reluctant to add this because I was concerned that an `.of(String string)` method might not be used properly (it should only be used with strings that use the Omni Core "JSON formatted" convention of _always_ using decimals in strings for divisible amounts and _never_ using decimals in strings of indivisible amounts.
But given that **OmniJ** itself already had multiple implementations of this method, I guess it makes sense to just add it to `OmniValue`.
I also tried to make the above concern well-documented in the JavaDoc.
=> OmniValue: add of(String) methods

omnij-jsonrpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendtomany/SendToManySpec.groovy
This pull request adds the new RPC `"omni_sendtomany"` with an example.
Please note, ideally we would pass a list of `Address` and `OmniValue` objects, instead of manually converting into strings within the test.
=> Add new RPC "omni_sendtomany" with example

omnij-jsonrpc/src/main/java/foundation/omni/json/pojo/OmniTradeInfo.java, omnij-jsonrpc/src/main/java/foundation/omni/rpc/OmniClient.java, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/AllPairDExActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/MetaDExActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/mdex/MetaDexSpec.groovy
* Add OmniTradeInfo class (POJO)
* Update OmniClient.omniGetTrade to use this POJO (instead of a Map)
* Add OmniClient.omniGetTradeHistoryForAddress() that returns a list of OmniTradeInfo
* Update tests to use POJO
* Add a partial test for omniGetTradeHistoryForAddress()
=> add OmniTradeInfo class for omniGetTrade and omniGetTradeHistoryForAddress

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanRawSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/rpc/RawTxDelegate.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy
The tests that need a RawRxBuilder have been changed to just allocate on locally.
=> Deprecate and stop using RawTxDelegate

gradle.properties, omnij-jsonrpc/src/main/java/foundation/omni/rpc/test/OmniTestClientAccessor.java, omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/activation/BaseActivationSpec.groovy, omnij-rpc/src/integ/groovy/foundation/omni/test/scripts/OmniCreateTokenScriptSpec.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestClientDelegate.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/OmniTestSupport.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/RegTestContext.groovy, omnij-rpc/src/main/groovy/foundation/omni/test/RegTestOmniFundingSource.groovy
* Update for significant changes in test class inheritance in CJ 0.6.4
* OmniTestSupport becomes an interface with default methods (was a trait)
* OmniTestClientAccessor interface is replacement for deprecated OmniTestClientDelegate
* @Ignore OmniCreateTokenScriptSpec (for now, at least)
=> Upgrade to ConsensusJ v0.6.4 (add support for Bitcoin Core v23.0)

omnij-jsonrpc/src/main/java/foundation/omni/json/pojo/OmniTransactionInfo.java, omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sendtomany/SendToManySpec.groovy
* OmniTransactionInfo: add totalAmount property
* SendToManySpec.groovy: use camel-case totalAmount
(This fixes failures that I found testing against the current develop branch where the test for the `omni_sendtomany` method succeeds and the SendToManySpec is run)
Depends on PR #215 (to avoid a merge)
=> OmniTransactionInfo: add totalAmount property for SendToMany

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy
I saw an intermittent and unexplained assertion failure (line 419, `assert thrown == exceptional`) in this method in a Github Actions run, so am adding this logging to (hopefully) catch it next time.
=> SendToOwnersTestPlanSpec.executeSendToOwners(): log exceptions

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/smartproperty/ManagedPropertySpec.groovy
Re-enable "Sending of granted tokens does not remove the limit of total tokens" test.
=> ManagedPropertySpec - re-enable sending-of-granted test

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy
Use a Java stream to initialize the `owners` list so that it is
effectively final and could be made immutable (e.g. by JDK 16+ `Stream.toList()`)
This is a child of PR #228
=> SendToOwnersTestPlanSpec: make owners effectively final/immutable

.github/workflows/graalvm.yml, CHANGELOG.adoc
Use the latest release and the new version numbering system.
=> GitHub graalvm workflow: Use latest GraalVM 17 (community)

omnij-rest-client-retrofit/build.gradle
Upgrade to the latest versions before OkHttp 4.x and Retrofit 3.x, respectively. (This is where the Kotlin dependency was introduced.)
=> Omni Retrofit REST client: OkHttp 3.14.9, Retrofit 2.9.0

omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/reorgs/SendToOwnersReorgSpec.groovy
Transaction is not part of blockchain anymore so it could not be part of omni database as well.
=> SendToOwnersReorgSpec: Use convenient function to check transaction validity
